
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switch.yaml

fan:
  - platform: xiaomi_miio
    name: Xiaomi Air Purifier
    host: 192.168.1.104
    token: !secret  Xiaomi_Air_Purifier_token
  - platform: xiaomi_miio
    name: XiaomiAirPurifier2S
    host: 192.168.1.103
    token: !secret  Xiaomi_Air_Purifier_2S_token
    model: zhimi.airpurifier.sa2 

sensor:
  - platform: template
    sensors:
      living_room_temp:
        friendly_name: 客廳溫度
        value_template: '{{ states.fan.XiaomiAirPurifier2S.attributes.temperature }}'
        unit_of_measurement: "°C" 
      living_room_aqi: 
        friendly_name: "客廳空氣質素" 
        unit_of_measurement: 'μg / m³' 
        value_template: "{{state_attr ('fan.XiaomiAirPurifier2S', 'aqi')}}"
      living_room_humidity: 
        friendly_name: "Humidity" 
        unit_of_measurement: '%' 
        value_template: "{{state_attr ('fan.XiaomiAirPurifier2S', 'humidity')}}"
      bedroom_aqi: 
        friendly_name: "睡房空氣質素" 
        unit_of_measurement: 'μg / m³' 
        value_template: "{{state_attr ('fan.xiaomi_air_purifier', 'aqi')}}"
      
    
remote:
  - platform: broadlink
    host: 192.168.1.154
    mac: !secret broadlink_mac
    name: RM Pro
    

browser_mod:
  prefix: "browsermod_"

yeelight:
  devices:
    192.168.1.95:
      name: Yeelight Light Strip
      model: strip1
      #ssdp_fallback: True
      #miio_token: "" # if provided miio protocol is used (optional)



homekit:
  filter:
    exclude_domains:
      - automation
      - input_boolean
    exclude_entity_globs:
      - light.browsermod_*
      - media_player.browsermod_*
      - sensor.browsermod_* 
      
frontend:
  themes: !include_dir_merge_named themes
  
  
sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  devices:
    1001042e0a:
      device_class: light
      name: 客廳燈
    100104bbdc:
      device_class: light
      name: 飯廳燈
  








        
        