- platform: broadlink
  host: 192.168.1.154
  mac: '78:0F:77:B9:45:76'
  switches:
    power:
      friendly_name: "電視"
      command_on: "JgBWAJSWEhQSORI5EjoSFBIUEhQSFBIUEjkSORI5ExQSFBIUEhQSFBIUEjkSORIUEhQSFBIUEjoSORIUEhQSORI5EjoTOBMABd6VlBI5EwAMepaTFTYWAA0FAAA="
      command_off: "JgBWAJSWEhQSORI5EjoSFBIUEhQSFBIUEjkSORI5ExQSFBIUEhQSFBIUEjkSORIUEhQSFBIUEjoSORIUEhQSORI5EjoTOBMABd6VlBI5EwAMepaTFTYWAA0FAAA="
    source:
      friendly_name: "電視 Source"
      command_on: "JgBSAJeVExMTORI5EjkSFBIVERQSFREUEjkTORI5EhQSFBIUEhQSORM5EjkSORIUEhQSFBIUEhQSFBMUEhQSORI5EjkSORMABd6UlhM4EgAMehcADQUAAAAAAAA="
      command_off: "JgBSAJeVExMTORI5EjkSFBIVERQSFREUEjkTORI5EhQSFBIUEhQSORM5EjkSORIUEhQSFBIUEhQSFBMUEhQSORI5EjkSORMABd6UlhM4EgAMehcADQUAAAAAAAA="
    tvup:
      friendly_name: "電視 Up"
      command_on: "JgBOAJWUExMTOBQ4EzgTExMTExMTExMTEzgUOBM4ExMTExMTExMTExM4ExMTExQSFBIUOBMTEzgTExM4EzgUOBM4ExMTOBMABd+VlBQ4EwANBQAAAAAAAAAAAAA="
      command_off: "JgBOAJWUExMTOBQ4EzgTExMTExMTExMTEzgUOBM4ExMTExMTExMTExM4ExMTExQSFBIUOBMTEzgTExM4EzgUOBM4ExMTOBMABd+VlBQ4EwANBQAAAAAAAAAAAAA="
    tvdown:
      friendly_name: "電視 Down"
      command_on: "JgBGAJaTFBIVNhU3FDcUEhQSFBIUEhQSFDcVNhU3FBIUEhQSFBIUNxQ3FREVERUSFBIUNxQSFBIUEhQ3FDcVNxQ3FBIUNxQADQUAAA=="
      command_off: "JgBGAJaTFBIVNhU3FDcUEhQSFBIUEhQSFDcVNhU3FBIUEhQSFBIUNxQ3FREVERUSFBIUNxQSFBIUEhQ3FDcVNxQ3FBIUNxQADQUAAA=="
    tvleft:
      friendly_name: "電視 Left"
      command_on: "JgBMAJWUExMTOBQ4EzgTExIUEhQSFBMTEzgTORI5ExMTExMTEhQTExIUEzgUEhMTFBMTOBMTEzgTOBQSEzgUOBI5EhQTOBMABd6VlRMADQUAAAAAAAAAAAAAAAA="
      command_off: "JgBMAJWUExMTOBQ4EzgTExIUEhQSFBMTEzgTORI5ExMTExMTEhQTExIUEzgUEhMTFBMTOBMTEzgTOBQSEzgUOBI5EhQTOBMABd6VlRMADQUAAAAAAAAAAAAAAAA="
    tvright:
      friendly_name: "電視 Right"
      command_on: "JgBGAJaTFREVNxQ3FDcVERURFREVERURFTYVNxQ3FREVERQSFREVNhURFTcUEhQSFBIUNxQSFREVNhURFTYVNxQ3FREVNhUADQUAAA=="
      command_off: "JgBGAJaTFREVNxQ3FDcVERURFREVERURFTYVNxQ3FREVERQSFREVNhURFTcUEhQSFBIUNxQSFREVNhURFTYVNxQ3FREVNhUADQUAAA=="
    volumeup:
      friendly_name: "Volume Up"
      command_on: "JgBOAJaUFBIUNxQ3FTYVERUSFBIUEhQSFDcUNxU2FREVEhQRFRIUEhQSFDcUEhQ3FBIUEhQSFDcVNxQSFDcUEhQ3FTYVNxQABamVlBQ3FAANBQAAAAAAAAAAAAA="
      command_off: "JgBOAJaUFBIUNxQ3FTYVERUSFBIUEhQSFDcUNxU2FREVEhQRFRIUEhQSFDcUEhQ3FBIUEhQSFDcVNxQSFDcUEhQ3FTYVNxQABamVlBQ3FAANBQAAAAAAAAAAAAA="
    volumedown:
      friendly_name: "Volume Down"
      command_on: "JgBOAJSVFREVNxI5EzgTExQSExMVERMTEzgUOBM4ExMUEhMTEhQUNxMTEzgVEhQ3ExMTExQSExMVNhMTEzgWEBY2EzgTOBMABd6XkhQ4EwANBQAAAAAAAAAAAAA="
      command_off: "JgBOAJSVFREVNxI5EzgTExQSExMVERMTEzgUOBM4ExMUEhMTEhQUNxMTEzgVEhQ3ExMTExQSExMVNhMTEzgWEBY2EzgTOBMABd6XkhQ4EwANBQAAAAAAAAAAAAA="
    tvback:
      friendly_name: "電視 Back"
      command_on: "JgBOAJSVExMWNRM4FDgTExURFBIUEhMTFjUTOBM5FREVERURFREVNhY1ExMWNhM4ExMVNhMTFhAWEBU2ExQUEhU2ExMTOBMABd+VlBM4FAANBQAAAAAAAAAAAAA="
      command_off: "JgBOAJSVExMWNRM4FDgTExURFBIUEhMTFjUTOBM5FREVERURFREVNhY1ExMWNhM4ExMVNhMTFhAWEBU2ExQUEhU2ExMTOBMABd+VlBM4FAANBQAAAAAAAAAAAAA="
    volumemute:
      friendly_name: "Volume Mute"
      command_on: "JgBOAJaTExMVNxM4EzgTExMTFRESFBIUFTYTORM4ExMUEhURExMVNhMTFDgUNxMTExMTExMTExMTOBQSFRETORQ3EzgTOBMABd"
      command_off: "JgBOAJaTExMVNxM4EzgTExMTFRESFBIUFTYTORM4ExMUEhURExMVNhMTFDgUNxMTExMTExMTExMTOBQSFRETORQ3EzgTOBMABd"
    tventer:
      friendly_name: "電視 Enter"
      command_on: "JgBOAJSVExMTORI5EjkUEhMTEhQTExMTFDgSORI5FBISFBMTExMTExM4EzkTExIUEhQSORQSEjkTExMTEzkSORI5EhQSORMABdyYlBQ3EwANBQAAAAAAAAAAAAA="
      command_off: "JgBOAJSVExMTORI5EjkUEhMTEhQTExMTFDgSORI5FBISFBMTExMTExM4EzkTExIUEhQSORQSEjkTExMTEzkSORI5EhQSORMABdyYlBQ3EwANBQAAAAAAAAAAAAA="